# -*- coding: utf-8 -*-
"""polygonal puzzle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SEfZO5aTDRAc4dibbF4qj-G_qQKULR-w
"""

