# -*- coding: utf-8 -*-
"""space pirate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RcZzMrVkLNXjFIAUjMZts4nbZ0Xgi3Bn
"""

